spring.application.name=Trabajo-Spring

spring.datasource.url=jdbc:postgresql://localhost:5432/trabajo_spring_db
spring.datasource.username=postgres
spring.datasource.password=a



spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha